services:
  postgres:
    image: postgres:18-alpine
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nyarikos
    volumes:
      - postgres_data:/var/lib/postgresql/data
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_container
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
      - DEFAULT_REGION=ap-southeast-3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - localstack-data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"

volumes:
  postgres_data:
  localstack-data: