services:
  postgres:
    restart: unless-stopped
    image: postgres:18-alpine
    container_name: postgres_container
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nyarikos
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data
  cdn:
    restart: unless-stopped
    image: nginx:alpine
    container_name: cdn_container
    ports:
      - "8001:80"
    depends_on:
      - localstack
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../uploads:/var/www/uploads
  localstack:
    restart: unless-stopped
    image: localstack/localstack:3.8.1
    container_name: localstack_container
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,sqs
      # - ACTIVATE_PRO=0
      # - DEBUG=1
      - DEFAULT_REGION=ap-southeast-3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      # - DATA_DIR=/var/lib/localstack/data
    volumes:
      # - localstack-data:/var/lib/localstack
      - "/var/run/docker.sock:/var/run/docker.sock"
      - ./init/aws/init-localstack.sh:/etc/localstack/init/ready.d/init.sh

volumes:
  postgres_data:
  localstack-data: